{% set name = "pytest_check_links" %}
{% set version = "0.4.2" %}

package:
  name: {{ name.replace("_", "-") }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0284a349473ccd941404df74a676a7e3db8e510ddd65f9c53b9eac32e4fb39da

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pytest-check-links = pytest_check_links.__main__:main

requirements:
  host:
    - pbr >=1.9
    - pip
    - python >=3.5
    - setuptools >=17.1
  run:
    - docutils
    - html5lib
    - nbconvert
    - nbformat
    - pytest >=2.8
    - python >=3.5
    - requests

test:
  imports:
    - pytest_check_links
  commands:
    - pip check
    - pytest-check-links --version
  requires:
    - pip

about:
  home: https://pypi.org/project/pytest-check-links
  summary: Check links in files
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/jupyterlab/pytest-check-links

extra:
  recipe-maintainers:
    - bollwyvl
